
   
name: ROS

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Test
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE $GITHUB_REPOSITORY \
          bash -c "
          vcs import --skip-existing < src/ros2.repos src \
          && apt-get update \
          && rosdep update \
          && rosdep install --from-paths src --ignore-src -y --rosdistro=foxy \
          && colcon build --cmake-args '-DCMAKE_BUILD_TYPE=Release' -Wall -Wextra -Wpedantic \
          && colcon test \
          "
